Feature 112 load idle page from api
Metatavu/muisti-exhibition-ui pull request #113
Opened 2021-01-14 22:50 UTC by MrWalrus3451

Resolves #112

2021-01-14 23:13 UTC, MrWalrus3451 commented on app/src/main/java/fi/metatavu/muisti/exhibitionui/views/MainActivity.kt
> +     * Checks if forced portrait mode setting is loaded and modifies UI accordingly
```suggestion
     * Checks if forced portrait mode setting is loaded and implements it
```

2021-01-14 23:13 UTC, MrWalrus3451 commented on app/src/main/java/fi/metatavu/muisti/exhibitionui/views/MainViewModel.kt
> +     * Returns the idle page Id for the current selected device
```suggestion
     * Returns the idle page Id for the current device
```

2021-01-15 06:11 UTC, anttileppa requested changes

2021-01-15 06:11 UTC, anttileppa commented on app/src/main/java/fi/metatavu/muisti/exhibitionui/views/MainActivity.kt
> +                //listenLoginButton(login_button)
Why this is commented out?

2021-01-15 06:11 UTC, anttileppa commented on app/src/main/java/fi/metatavu/muisti/exhibitionui/views/MainActivity.kt
> +    private fun openIdlePage(idlePage: PageView) {
Add docs

2021-01-15 06:11 UTC, anttileppa commented on app/src/main/java/fi/metatavu/muisti/exhibitionui/views/MainViewModel.kt
> +    suspend fun getIdlePageId() : UUID? {
Fix comments

2021-01-26 06:31 UTC, merged